#!/bin/sh -e

HEREDIR=$(/bin/readlink -f $(/usr/bin/dirname $0))

if [ -n "$FAUX_DIG_KEY" ]; then
	eval set -- $(/usr/bin/getopt -o k: -- "$@")
	while /bin/true; do
		case "$1" in
			-k)
				if [ "$2" = "$FAUX_DIG_KEY" ]; then
					key_ok=1
				else
					key_ok=0
				fi
				shift 2
				;;
			--)
				shift
				break
				;;
		esac
	done
	
	if [ "$key_ok" != "1" ]; then
		exit 1
	fi
fi

if [ "$1" = "notarealdomain" ]; then
	/bin/echo "I really love this stuff"
elif [ "$1" = "@127.0.0.1" -a "$2" = "IN" -a "$3" = "AXFR" ]; then
	/bin/cat $HEREDIR/$4
else
	/bin/echo "Arguments unknown"
	exit 1
fi
